swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  # describe get requests at the baseUrl endpoint
  /:
    # the operation we want to describe at / - GET  
    get:
      # a long description of the operation.
      # summary can also be used for shorter ones
      description: "A description: This endpoint returns all todos in database"
      summary: "A shorter summary of the operation"
      # operationId is a unique string used to identify an operation
      # GET is the operation
      operationId: "GetAllTodos"
      parameters: []
      responses:
        "200":
          description: "an array of todos"
          schema:
            type: "array"
            items:
              # reference the definition of Todo
              $ref: "#/definitions/Todo"
  /swagger:
    x-swagger-pipe: swagger_raw
# in open API 3 this sections is called components/schemas instead of
# definitions
definitions:
  Todo:
    type: object
    # Specify the properties of an object
    # All properties are optional by default.
    # A required list can be created to adjust which properties are required:
    # required:
    #   - todo_id
    #   - todo
    # 'required' is object-level - not property level
    properties:
      # each property must have its own schema defined
      todo_id:
        type: "integer"
        description: "Id for the todo"
        # poperties can be defined as read only:
        # readOnly: true
      todo:
        type: "string"
        description: "The todo itself"
      datecreated:
        type: "string"
        format: "date-time"
        description: "The date the todo was created. Set by server"
      author:
        type: "string"
        description: "Name of the person who created the todo"
      duedate:
        type: "string"
        format: "date-time"
        description: "Date the todo is due"
      completed: 
        type: "boolean"
        description: "Indicate if the todo is completed or not"
    