swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo API
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: "A description: This endpoint returns all todos in database"
      summary: "A shorter summary of the operation"
      operationId: "GetAllTodos"
      parameters: []
      responses:
        "200":
          description: "an array of todos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
    post:
      description: 'Add a new Todo'
      operationId: 'AddTodo'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'todo'
          description: 'the Todo to be added'
          required: true
          schema:
            $ref: "#/definitions/Todo"
      responses:
        '201':
          description: 'Successful Todo add'
      x-swagger-router-controller: "AddTodo"

  /todo/{id}:
    get:
      description: 'Retrieve a single todo by id'
      operationId: 'FindTodoById'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Id of the todo to get'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Todo response'
          schema:
            $ref: "#/definitions/Todo"
      x-swagger-router-controller: 'FindTodoById'

    delete:
      description: 'delete a todo by id'
      operationId: 'DeleteTodoById'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Id of the Todo to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '204':
          description: 'todo deleted'
      x-swagger-router-controller: 'DeleteTodoById'

    # add a method to allow for updating a user by id
    put:
      # describe what the endpoint does
      description: 'update a single todo by id'
      operationId: 'UpdateTodoById'
      parameters:
        # we need a parameter to indicate which todo we're updating
        - name: 'id'
          # which we get from the path
          in: 'path'
          description: 'the id to update'
          # and is an integer
          type: 'integer'
          # which is 64-bit
          format: 'int46'
          # and is required because it has to be in the path for us to 
          # update anything
          required: true
        # we also need the actual object that will be used to update 
        # the todo
        - name: 'updated_todo'
          # which we will send through in the body of the request
          in: 'body'
          # and is also required, otherwise we have nothing to update our
          # todo with
          required: true
          # we've already defined the schema, so we can reference it from
          # our existing definition
          schema:
            $ref: "#/definitions/Todo"
      # as always, we need to provide a response to a request from the
      # client
      responses:
        # we can say the update was successful
        '200':
          description: 'todo updated'
        # otherwise we can indicate there was some error in the request 
        # using a 4XX response
        '400':
          description: 'error updating todo'
      x-swagger-router-controller: 'UpdateTodoById'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Todo:
    type: object
    properties:
      todo_id:
        type: "integer"
        description: "Id for the todo"
      todo:
        type: "string"
        description: "The todo itself"
      datecreated:
        type: "string"
        format: "date-time"
        description: "The date the todo was created. Set by server"
      author:
        type: "string"
        description: "Name of the person who created the todo"
      duedate:
        type: "string"
        format: "date-time"
        description: "Date the todo is due"
      completed:
        type: "boolean"
        description: "Indicate if the todo is completed or not"

