swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo API
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: "A description: This endpoint returns all todos in database"
      summary: "A shorter summary of the operation"
      operationId: "GetAllTodos"
      parameters: []
      responses:
        "200":
          description: "an array of todos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
      x-swagger-router-controller: "GetAllTodos"
    # we'll now create a handler for this post request
    post:
      description: 'Add a new Todo'
      # this is the function that swagger will look for in the file defined
      # by x-swagger-router-controller
      operationId: 'AddTodo'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'todo'
          description: 'the Todo to be added'
          required: true
          schema:
            $ref: "#/definitions/Todo"
      responses:
        # we only define a 201 here, but we should likely also define a 409
        '201':
          description: 'Successful Todo add'
          # we have to set the schema of the response
          # otherwise swagger throws an error that void cannot have a value. 
          # It expects nothing if you don't define a schema
          # With a POST request you should return the same
          # as if a GET request was made against the same resource
          # So we want a JSON response of the created object
          schema:
            $ref: "#/definitions/Todo"
      # this is the name of the file swagger will use to look for a named export
      # of a function that we specify at operationId
      x-swagger-router-controller: "AddTodo"

  /todo/{id}:
    get:
      description: 'Retrieve a single todo by id'
      operationId: 'FindTodoById'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Id of the todo to get'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Todo response'
          schema:
            $ref: "#/definitions/Todo"
      x-swagger-router-controller: 'FindTodoById'

    delete:
      description: 'delete a todo by id'
      operationId: 'DeleteTodoById'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Id of the Todo to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '204':
          description: 'todo deleted'
      x-swagger-router-controller: 'DeleteTodoById'

    put:
      description: 'update a single todo by id'
      operationId: 'UpdateTodoById'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'the id to update'
          type: 'integer'
          format: 'int46'
          required: true
        - name: 'updated_todo'
          in: 'body'
          required: true
          schema:
            $ref: "#/definitions/Todo"
      responses:
        '200':
          description: 'todo updated'
        '400':
          description: 'error updating todo'
      x-swagger-router-controller: 'UpdateTodoById'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Todo:
    type: object
    properties:
      todo_id:
        type: "integer"
        description: "Id for the todo"
      todo:
        type: "string"
        description: "The todo itself"
      datecreated:
        type: "string"
        format: "date-time"
        description: "The date the todo was created. Set by server"
      author:
        type: "string"
        description: "Name of the person who created the todo"
      duedate:
        type: "string"
        format: "date-time"
        description: "Date the todo is due"
      completed:
        type: "boolean"
        description: "Indicate if the todo is completed or not"

